name: Publish WildRift Data to Github Pages

on:
  push:
    branches:
      - master
  schedule:
    # Run every night at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CI: true

jobs:
  publish-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Step 1
      - name: checkout code
        uses: actions/checkout@v3
      # Step 2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      # Step 2.1: Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      # Step 2.2: Install dependencies
      - name: Install dependencies
        run: pnpm install --production
      # Step 3: Run the JavaScript script from dist/ directory
      - name: Run script
        run: node dist/main.js || node dist/main.js || node dist/main.js
      # Step 4: Push public/ to gh-pages
      - name: Push public/ to gh-pages and Deploy pages to Github Pages
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add gh-pages-remote https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git fetch --no-recurse-submodules
          # Set up worktree and deploy
          git worktree add ./gh-pages gh-pages || true
          cd gh-pages
          git rm -r .
          cp -r ../public/. .
          git add .
          # Is there change?
          if git diff --quiet HEAD; then
              echo "No changes detected Skipping push."
              exit 0
          fi
          git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
          git push gh-pages-remote gh-pages:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
